[
  {
    data: {
      id: "1",
      label: "amount of collected data",
    },
    classes: "primary",
  },
  {
    data: {
      id: "2",
      label: "level of privacy risk",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "3",
      label: "level of awareness",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "4",
      label: "level of regulation",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "5",
      label: "degree to which people are sensitised",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "6",
      label: "level of people's approval to data collection",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "7",
      label: "quality of services",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "8",
      label: "profit generated by data collecting entities",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "9",
      label: "investment in data collecting initiatives",
    },
    classes: "secondary",
  },
  {
    data: {
      id: "1->2",
      source: "1",
      target: "2",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "2->3",
      source: "2",
      target: "3",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "3->4",
      source: "3",
      target: "4",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "4->1",
      source: "4",
      target: "1",
      label: "-",
      type: "negative",
    },
  },
  {
    data: {
      id: "1->5",
      source: "1",
      target: "5",
      label: "-",
      type: "negative",
    },
  },
  {
    data: {
      id: "5->3",
      source: "5",
      target: "3",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "3->6",
      source: "3",
      target: "6",
      label: "-",
      type: "negative",
    },
  },
  {
    data: {
      id: "6->1",
      source: "6",
      target: "1",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "1->7",
      source: "1",
      target: "7",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "7->8",
      source: "7",
      target: "8",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "8->9",
      source: "8",
      target: "9",
      label: "+",
      type: "positive",
    },
  },
  {
    data: {
      id: "9->1",
      source: "9",
      target: "1",
      label: "+",
      type: "positive",
    },
  },
];
